"""Модели для работы с разделами анкеты

Revision ID: 95a2c494a388
Revises: ddfb079a6d8f
Create Date: 2024-07-31 14:08:43.134909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a2c494a388'
down_revision = 'ddfb079a6d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('ankets_uuid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ankets_uuid'], ['ankets.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sorting', sa.Integer(), nullable=True),
    sa.Column('ankets_uuid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ankets_uuid'], ['ankets.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('information')
    op.drop_table('files')
    # ### end Alembic commands ###
