"""Модели для работы с файлами

Revision ID: ad6867f10f42
Revises: 95a2c494a388
Create Date: 2024-07-31 15:52:05.638000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6867f10f42'
down_revision = '95a2c494a388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('columns', sa.Integer(), nullable=True),
    sa.Column('sorting', sa.Integer(), nullable=True),
    sa.Column('ankets_uuid', sa.String(), nullable=False),
    sa.Column('chapters_id', sa.Integer(), nullable=True),
    sa.Column('dependent_field_uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ankets_uuid'], ['ankets.uuid'], ),
    sa.ForeignKeyConstraint(['chapters_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['dependent_field_uuid'], ['fields.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sections')
    op.drop_table('fields')
    op.drop_table('chapters')
    # ### end Alembic commands ###
