"""remove unique for label anket

Revision ID: ddfb079a6d8f
Revises: 89c8794dbd8d
Create Date: 2024-07-29 18:50:00.511241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddfb079a6d8f'
down_revision = '89c8794dbd8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ankets_label_key', 'ankets', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ankets_label_key', 'ankets', ['label'])
    # ### end Alembic commands ###
